### PR TITLE
Encode POST and GET parameters in utf-8

### PR DESCRIPTION
**Pull request by jjdlugosz**
Propose a change to selena-agent which encodes all URL parameters in GET or POST request in 'utf-8'. Without the change some controllers (specially which supports only POST request) do not accept HTTP request
This change follows appriopriate changes in selena project.

### CODE REVIEW

**Comment by deejay1** [comment]
Ah, yes, I didn't scroll to the top enough, sorry.
+1 then!

**Comment by pawellesniewski** [comment]
+1

**Comment by deejay1** [comment]
@jjdlugosz Argh, merge conflict :/

**Comment by jjdlugosz** [comment]
Should be OK now

**Comment by deejay1** [comment]
+1

**Pull request merged**
